-- Create operational tables
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    MSISDN VARCHAR2(15) UNIQUE NOT NULL,
    CUSTOMER_NAME VARCHAR2(100),
    REGION VARCHAR2(50),
    ZONE VARCHAR2(50),
    CITY VARCHAR2(50),
    REGISTRATION_DATE DATE,
    CUSTOMER_TYPE VARCHAR2(20),
    TARIFF_PLAN VARCHAR2(30),
    ACCOUNT_STATUS VARCHAR2(20)
);

CREATE TABLE CALL_DETAIL_RECORDS (
    CDR_ID NUMBER PRIMARY KEY,
    CALLING_MSISDN VARCHAR2(15) NOT NULL,
    CALLED_MSISDN VARCHAR2(15) NOT NULL,
    CALL_START_TIME TIMESTAMP,
    CALL_END_TIME TIMESTAMP,
    CALL_DURATION_SECONDS NUMBER,
    CALL_TYPE VARCHAR2(20),
    CELL_ID VARCHAR2(20),
    IMSI VARCHAR2(20),
    IMEI VARCHAR2(20),
    CALL_CHARGE NUMBER(10,2)
);

CREATE TABLE DATA_USAGE (
    DATA_ID NUMBER PRIMARY KEY,
    MSISDN VARCHAR2(15) NOT NULL,
    SESSION_START_TIME TIMESTAMP,
    SESSION_END_TIME TIMESTAMP,
    DATA_VOLUME_MB NUMBER(10,2),
    SERVICE_TYPE VARCHAR2(30),
    APN VARCHAR2(50),
    CHARGE_AMOUNT NUMBER(10,2)
);

CREATE TABLE SMS_RECORDS (
    SMS_ID NUMBER PRIMARY KEY,
    SENDER_MSISDN VARCHAR2(15),
    RECEIVER_MSISDN VARCHAR2(15),
    SMS_TIMESTAMP TIMESTAMP,
    SMS_TYPE VARCHAR2(20),
    SMS_LENGTH NUMBER,
    SMS_CHARGE NUMBER(10,2)
);

CREATE TABLE FINANCIAL_TRANSACTIONS (
    TRANSACTION_ID NUMBER PRIMARY KEY,
    MSISDN VARCHAR2(15),
    TRANSACTION_TYPE VARCHAR2(30),
    TRANSACTION_AMOUNT NUMBER(10,2),
    TRANSACTION_DATE DATE,
    PAYMENT_METHOD VARCHAR2(30),
    BALANCE_BEFORE NUMBER(10,2),
    BALANCE_AFTER NUMBER(10,2)
);

