-- ============================================
-- 6 DIMENSION TABLES
-- ============================================

-- 1. CUSTOMER Dimension
CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_SK INT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    MSISDN VARCHAR(15) NOT NULL,
    CUSTOMER_NAME VARCHAR(100),
    REGION VARCHAR(50),
    ZONE VARCHAR(50),
    CITY VARCHAR(50),
    CUSTOMER_TYPE VARCHAR(20),
    TARIFF_PLAN VARCHAR(30),
    ACCOUNT_STATUS VARCHAR(20),
    REGISTRATION_DATE DATE
);

-- 2. TIME Dimension
CREATE TABLE DIM_TIME (
    TIME_ID INT PRIMARY KEY,
    DATE_TIME DATETIME2 NOT NULL,
    DATE_ONLY DATE NOT NULL,
    YEAR INT NOT NULL,
    QUARTER TINYINT NOT NULL,
    MONTH TINYINT NOT NULL,
    DAY TINYINT NOT NULL,
    HOUR TINYINT NOT NULL,
    DAY_OF_WEEK VARCHAR(20),
    IS_WEEKEND CHAR(1),
    IS_BUSINESS_HOUR CHAR(1)
);

-- 3. SERVICE Dimension
CREATE TABLE DIM_SERVICE (
    SERVICE_ID INT PRIMARY KEY,
    SERVICE_TYPE VARCHAR(30) NOT NULL,
    SERVICE_CATEGORY VARCHAR(20) NOT NULL,
    CHARGE_TYPE VARCHAR(20),
    IS_PREPAID CHAR(1),
    IS_ROAMING CHAR(1)
);

-- 4. LOCATION Dimension
CREATE TABLE DIM_LOCATION (
    LOCATION_ID INT PRIMARY KEY,
    CELL_ID VARCHAR(20),
    REGION VARCHAR(50),
    ZONE VARCHAR(50),
    CITY VARCHAR(50),
    LOCATION_TYPE VARCHAR(30)
);

-- 5. DEVICE Dimension
CREATE TABLE DIM_DEVICE (
    DEVICE_ID INT PRIMARY KEY,
    IMEI VARCHAR(20),
    IMSI VARCHAR(20),
    DEVICE_TYPE VARCHAR(30),
    DEVICE_MODEL VARCHAR(50),
    MANUFACTURER VARCHAR(50)
);

-- 6. PAYMENT Dimension
CREATE TABLE DIM_PAYMENT (
    PAYMENT_ID INT PRIMARY KEY,
    PAYMENT_METHOD VARCHAR(30),
    PAYMENT_CHANNEL VARCHAR(30),
    PAYMENT_STATUS VARCHAR(20)
);

-- ============================================
-- SINGLE FACT TABLE
-- ============================================

CREATE TABLE FACT_TELECOM_ANALYTICS (
    -- Foreign Keys to all 6 Dimensions
    CUSTOMER_SK INT NOT NULL,
    TIME_ID INT NOT NULL,
    SERVICE_ID INT NOT NULL,
    LOCATION_ID INT NULL,
    DEVICE_ID INT NULL,
    PAYMENT_ID INT NULL,
    
    -- Degenerated Dimensions (from source)
    CALLING_MSISDN VARCHAR(15),
    CALLED_MSISDN VARCHAR(15),
    CELL_ID VARCHAR(20),
    TRANSACTION_REF VARCHAR(50),
    
    -- Facts/Measures
    DURATION_SECONDS INT NULL,
    DATA_VOLUME_MB DECIMAL(10,2) NULL,
    CALL_COUNT INT DEFAULT 1,
    SMS_COUNT INT DEFAULT 1,
    DATA_SESSION_COUNT INT DEFAULT 1,
    TRANSACTION_COUNT INT DEFAULT 1,
    AMOUNT DECIMAL(10,2) NULL,
    CHARGE_AMOUNT DECIMAL(10,2) NULL,
    BALANCE_BEFORE DECIMAL(10,2) NULL,
    BALANCE_AFTER DECIMAL(10,2) NULL,
    
    -- Flags
    IS_SUCCESSFUL CHAR(1),
    IS_INTERNATIONAL CHAR(1),
    IS_ROAMING CHAR(1),
    IS_ONNET CHAR(1),
    SOURCE_SYSTEM VARCHAR(20),
    
    -- Constraints
    CONSTRAINT PK_FACT_TELECOM PRIMARY KEY (CUSTOMER_SK, TIME_ID, SERVICE_ID, SOURCE_SYSTEM),
    CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_SK) REFERENCES DIM_CUSTOMER(CUSTOMER_SK),
    CONSTRAINT FK_TIME FOREIGN KEY (TIME_ID) REFERENCES DIM_TIME(TIME_ID),
    CONSTRAINT FK_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES DIM_SERVICE(SERVICE_ID),
    CONSTRAINT FK_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES DIM_LOCATION(LOCATION_ID),
    CONSTRAINT FK_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DIM_DEVICE(DEVICE_ID),
    CONSTRAINT FK_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES DIM_PAYMENT(PAYMENT_ID)
);

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX IDX_FACT_CUSTOMER ON FACT_TELECOM_ANALYTICS(CUSTOMER_SK);
CREATE INDEX IDX_FACT_TIME ON FACT_TELECOM_ANALYTICS(TIME_ID);
CREATE INDEX IDX_FACT_SERVICE ON FACT_TELECOM_ANALYTICS(SERVICE_ID);
CREATE INDEX IDX_FACT_CUST_TIME ON FACT_TELECOM_ANALYTICS(CUSTOMER_SK, TIME_ID);
CREATE INDEX IDX_FACT_SOURCE ON FACT_TELECOM_ANALYTICS(SOURCE_SYSTEM);
CREATE INDEX IDX_FACT_COMPOSITE ON FACT_TELECOM_ANALYTICS(CUSTOMER_SK, TIME_ID, SERVICE_ID);

-- ============================================
-- SEQUENCES (SQL Server 2012+)
-- ============================================

CREATE SEQUENCE SEQ_CUSTOMER_SK START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TIME_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SERVICE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOCATION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DEVICE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PAYMENT_ID START WITH 1 INCREMENT BY 1;